name: ci
on: [push, pull_request]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: verify
        run: mvn -B verify